name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine
      volumes:
        - /artifacts:/artifacts
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        go build -mod=vendor -o binary $GITHUB_WORKSPACE/main.go
        mkdir /artifacts && cp binary /artifacts/binary
    - uses: actions/upload-artifact@v2-preview
      with:
        name: binary
        path: /artifacts
        key: binary
  deploy-terraform:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      volumes:
        - /artifacts:/artifacts
      env:
        AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:        
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: binary
        path: $GITHUB_WORKSPACE
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./deploy/lambda.zip . -i binary
    - name: Deploy
      working-directory: ./deploy
      run: |
        terraform init
        terraform apply
