name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine
      volumes:
        - /artifacts:/artifacts
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        go build -mod=vendor -o binary $GITHUB_WORKSPACE/main.go
        mkdir /artifacts && cp binary /artifacts/binary
    - uses: actions/upload-artifact@v2-preview
      with:
        name: binary
        path: /artifacts
        key: binary
  deploy-terraform:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      volumes:
        - /artifacts:/artifacts
    steps:        
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v1
      with:
        name: binary
        path: $GITHUB_WORKSPACE
      
    - name: Deploy
      run: terraform apply $GITHUB_WORKSPACE/deploy/main.tf
