name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.14'
    
    - uses: actions/checkout@v2  
    
    - name: Build
      run: |
        go build -mod=vendor -o binary main.go
    
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./deploy/lambda.zip . -i binary
    
    - uses: actions/upload-artifact@v2-preview
      with:
        name: lambda-zip
        path: deploy/lambda.zip
        key: lambda.zip
     
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.24
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: deploy
        tf_actions_comment: false
              
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.12
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: deploy
        tf_actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_role_arn: ${{ secrets.TF_VAR_role_arn }}    
    
   
