name: Tests
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        stable: 'true'
        go-version: '1.14'
    - name: Tests lambda can be build with vendor
      run: go build -mod=vendor main.go
      
    - name: Run tests
      run: go test ./...
      
